name: toolchain-build

on:
  push:
    branches: [ "docker_cmake_build" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xinshengwen/telink-dev-gcc12.2:1.0.0

    env:
      PLATFORM: TL_PLATFORM_SDK_751X
      APP_NAME: ADC_Demo
      BUILD_CMD: run_cmake.sh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix script permission
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;

      - name: Build
        run: |
          echo "Platform: $PLATFORM"
          ${BUILD_CMD} $PLATFORM $APP_NAME

      - name: Collect artifacts
        run: |
          mkdir -p artifacts

          find cmake_builds -type f \( \
            -name "*.bin" -o \
            -name "*.elf" -o \
            -name "*.lst" \
          \) -exec cp --parents {} artifacts/ \;

          echo "Artifacts:"
          find artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: artifacts/
          retention-days: 7
